import assert from "node:assert/strict";
import { loadBrowserModule } from "./load-browser-module.mjs";

const {
  buildAssignmentResultsFraming,
  buildAssignmentSourceFilterCounts,
  buildAssignmentSourceViewModel,
  buildAutomationRunFeedbackNotice,
  buildAutomationRunOutcomeViewModel,
  buildAutomationRunStaleState,
  buildAutomationRerunSafetyCopy,
  buildCoverageWarningDisplay,
  buildGeneratedAssignmentExplainabilitySummary,
  buildRecentPersonalisedRunActivityRows,
  doesAssignmentSourceMatchFilter,
  getAssignmentSourceFilterKey,
  getAssignmentSourceFilterOptions,
  formatCoverageWarningCopy,
  getAutomationRunReasonLabel,
  getAutomationRunStatusLabel,
  summarizeAutomationRunSkipReasons,
  summarizeAutomationRunWaitingReasons,
} = await loadBrowserModule("../js/automationRunFeedback.js", import.meta.url);

const TESTS = [];

function test(name, fn) {
  TESTS.push({ name, fn });
}

function plain(value) {
  return JSON.parse(JSON.stringify(value));
}

test("assignment source labels distinguish teacher policy legacy baseline and Bee cases", () => {
  const run = {
    id: "run-1",
    policy_snapshot: { name: "Year 7 weekly" },
    finished_at: "2026-05-25T09:30:00Z",
  };

  assert.deepEqual(
    plain(buildAssignmentSourceViewModel({ assignment: { id: "teacher-1" } })),
    {
      key: "teacher_created",
      label: "Teacher-created",
      tone: "neutral",
      detail: "Created manually by a teacher.",
      runId: "",
      runMatched: false,
      policyName: "",
      timestamp: "",
    }
  );
  assert.equal(
    buildAssignmentSourceViewModel({
      assignment: {
        automation_kind: "personalised",
        automation_source: "manual_run_now",
        automation_run_id: "run-1",
      },
      isGenerated: true,
      run,
    }).label,
    "Generated by policy"
  );
  assert.equal(
    buildAssignmentSourceViewModel({ assignment: {}, isGenerated: true }).label,
    "Legacy personalised"
  );
  assert.equal(
    buildAssignmentSourceViewModel({ assignment: {}, isBaseline: true }).label,
    "Baseline"
  );
  assert.equal(
    buildAssignmentSourceViewModel({ assignment: { automation_kind: "spelling_bee" }, isSpellingBee: true }).label,
    "Spelling Bee"
  );
});

test("assignment source filter maps known source keys to source groups", () => {
  const labelsByKey = Object.fromEntries(
    getAssignmentSourceFilterOptions().map((option) => [option.key, option.label])
  );

  assert.equal(labelsByKey[getAssignmentSourceFilterKey("generated_by_policy")], "Automated");
  assert.equal(labelsByKey[getAssignmentSourceFilterKey("legacy_personalised")], "Automated");
  assert.equal(labelsByKey[getAssignmentSourceFilterKey("teacher_created")], "Teacher-created");
  assert.equal(labelsByKey[getAssignmentSourceFilterKey("baseline")], "Baseline");
  assert.equal(labelsByKey[getAssignmentSourceFilterKey("spelling_bee")], "Spelling Bee");
});

test("all sources filter matches all known source keys", () => {
  for (const sourceKey of [
    "generated_by_policy",
    "legacy_personalised",
    "teacher_created",
    "baseline",
    "spelling_bee",
  ]) {
    assert.equal(doesAssignmentSourceMatchFilter(sourceKey, "all"), true);
  }
});

test("assignment source filter counts include all sources and each source group", () => {
  const counts = buildAssignmentSourceFilterCounts([
    "generated_by_policy",
    "legacy_personalised",
    "teacher_created",
    "baseline",
    "spelling_bee",
    "generated_by_policy",
  ]);

  assert.deepEqual(plain(counts), {
    all: 6,
    automated: 3,
    teacher_created: 1,
    baseline: 1,
    spelling_bee: 1,
  });
});

test("assignment results framing distinguishes personalised outcomes from standard results", () => {
  assert.deepEqual(
    plain(buildAssignmentResultsFraming("teacher_created")),
    {
      closedButtonLabel: "View results",
      openButtonLabel: "Hide results",
      resultsHeading: "Results",
      progressHeading: "Class progress",
      introNote: "",
    }
  );

  assert.deepEqual(
    plain(buildAssignmentResultsFraming("generated_by_policy")),
    {
      closedButtonLabel: "View personalised outcomes",
      openButtonLabel: "Hide personalised outcomes",
      resultsHeading: "Personalised outcomes",
      progressHeading: "Personalised progress",
      introNote: "Each pupil may have received a personalised word set. Use this view to compare completion, accuracy and target progress, not identical question-by-question scores.",
    }
  );

  assert.deepEqual(
    plain(buildAssignmentResultsFraming("legacy_personalised")),
    plain(buildAssignmentResultsFraming("generated_by_policy"))
  );

  assert.deepEqual(
    plain(buildAssignmentResultsFraming("baseline")),
    plain(buildAssignmentResultsFraming("teacher_created"))
  );

  assert.deepEqual(
    plain(buildAssignmentResultsFraming("")),
    plain(buildAssignmentResultsFraming("teacher_created"))
  );
});

test("0 included baseline_incomplete returns warning with waiting copy", () => {
  const notice = buildAutomationRunFeedbackNotice({
    classResults: [{
      status: "waiting",
      waitingCount: 11,
      waitingReasons: { baseline_incomplete: 11 },
    }],
    includedPupilCount: 0,
    skippedPupilCount: 0,
    waitingPupilCount: 11,
    errorCount: 0,
  });

  assert.equal(notice.type, "warning");
  assert.equal(
    notice.message,
    "No personalised tests generated. 11 pupils were waiting for baseline. They need to complete baseline before personalised tests can be generated."
  );
  assert.equal(notice.message.includes("skipped because they have not completed baseline"), false);
});

test("0 included no_baseline_assignment returns warning with waiting setup copy", () => {
  const notice = buildAutomationRunFeedbackNotice({
    classResults: [{
      status: "waiting",
      waitingCount: 11,
      waitingReasons: { no_baseline_assignment: 11 },
    }],
    includedPupilCount: 0,
    skippedPupilCount: 0,
    waitingPupilCount: 11,
    errorCount: 0,
  });

  assert.equal(notice.type, "warning");
  assert.equal(
    notice.message,
    "No personalised tests generated. 11 pupils were waiting for baseline. Baseline tests are created automatically when pupils log in, or use Baseline status to provision them now."
  );
  assert.equal(notice.message.includes("skipped because they do not have a baseline assignment"), false);
});

test("included waiting and skipped pupils returns partial warning copy", () => {
  const notice = buildAutomationRunFeedbackNotice({
    classResults: [{
      status: "generated",
      waitingCount: 2,
      skippedCount: 1,
      waitingReasons: {
        baseline_incomplete: 2,
      },
      skipReasons: {
        active_automated_assignment: 1,
      },
    }],
    includedPupilCount: 5,
    skippedPupilCount: 1,
    waitingPupilCount: 2,
    errorCount: 0,
  });

  assert.equal(notice.type, "warning");
  assert.match(notice.message, /Generated 1 personalised test\./);
  assert.match(notice.message, /Included 5 pupils\./);
  assert.match(notice.message, /2 pupils were waiting for baseline\./);
  assert.match(notice.message, /Skipped 1 pupil\./);
  assert.match(notice.message, /1 pupil already has an active personalised assignment\./);
});

test("included without skipped pupils returns success", () => {
  const notice = buildAutomationRunFeedbackNotice({
    classResults: [{ status: "generated", waitingCount: 0, skippedCount: 0, waitingReasons: {}, skipReasons: {} }],
    includedPupilCount: 5,
    skippedPupilCount: 0,
    waitingPupilCount: 0,
    errorCount: 0,
  });

  assert.equal(notice.type, "success");
  assert.equal(notice.message, "Generated 1 personalised test. Included 5 pupils.");
});

test("skip reason counts are grouped across classes", () => {
  const counts = summarizeAutomationRunSkipReasons([
    { skipReasons: { active_automated_assignment: 1 } },
    { skipReasons: { duplicate_pupil_in_run: 2 } },
  ]);

  assert.deepEqual(plain(counts), {
    active_automated_assignment: 1,
    duplicate_pupil_in_run: 2,
  });
});

test("waiting reason counts are grouped separately from skipped reasons", () => {
  const waitingCounts = summarizeAutomationRunWaitingReasons([
    { waitingReasons: { baseline_incomplete: 2 } },
    { waitingReasons: { baseline_incomplete: 3, no_baseline_assignment: 1 } },
  ]);
  const skipCounts = summarizeAutomationRunSkipReasons([
    { waitingReasons: { baseline_incomplete: 5 } },
    { skipReasons: { active_automated_assignment: 1 } },
  ]);

  assert.deepEqual(plain(waitingCounts), {
    baseline_incomplete: 5,
    no_baseline_assignment: 1,
  });
  assert.deepEqual(plain(skipCounts), {
    active_automated_assignment: 1,
  });
});

test("active personalised assignment remains a skipped blocked case", () => {
  const notice = buildAutomationRunFeedbackNotice({
    classResults: [{
      status: "skipped",
      skippedCount: 1,
      skipReasons: { active_automated_assignment: 1 },
    }],
    includedPupilCount: 0,
    skippedPupilCount: 1,
    waitingPupilCount: 0,
    errorCount: 0,
  });

  assert.equal(notice.type, "warning");
  assert.equal(
    notice.message,
    "No personalised tests generated. 1 pupil already has an active personalised assignment."
  );
});

test("run outcome view model groups status and reason copy", () => {
  const view = buildAutomationRunOutcomeViewModel({
    run: {
      status: "completed",
      included_pupil_count: 3,
      skipped_pupil_count: 2,
      summary: {
        waitingPupilCount: 2,
        errorCount: 1,
        coverageWarnings: [],
        classes: [{
          className: "Maple",
          status: "generated",
          includedCount: 3,
          waitingCount: 2,
          skippedCount: 2,
          waitingReasons: {
            baseline_incomplete: 1,
            no_baseline_assignment: 1,
          },
          skipReasons: {
            active_automated_assignment: 1,
            duplicate_pupil_in_run: 1,
          },
          coverageWarnings: [],
        }],
      },
      pupilRows: [
        { status: "included" },
        { status: "waiting", skip_reason: "baseline_incomplete" },
        { status: "skipped", skip_reason: "active_automated_assignment" },
      ],
    },
  });

  assert.equal(view.headline, "3 pupils generated/provisioned");
  assert.equal(view.counts.waiting, 2);
  assert.equal(view.counts.alreadyAssigned, 1);
  assert.equal(view.counts.duplicate, 1);
  assert.equal(view.counts.errors, 1);
  assert.match(view.rerunSafetyCopy, /Already assigned pupils were left untouched/);
  assert.match(view.rerunSafetyCopy, /baseline completion/);
  assert.match(view.rerunSafetyCopy, /Duplicate group memberships were skipped/);
  assert.deepEqual(
    plain(view.reasonChips.map((item) => `${item.label}:${item.count}`)),
    [
      "Already assigned:1",
      "Baseline incomplete:1",
      "Baseline not created yet:1",
      "Duplicate group membership:1",
    ]
  );
});

test("stale running run returns teacher-facing incomplete run copy", () => {
  const run = {
    status: "running",
    started_at: "2026-05-25T10:00:00Z",
    updated_at: "2026-05-25T10:01:00Z",
    finished_at: null,
  };
  const stale = buildAutomationRunStaleState(run, {
    now: new Date("2026-05-25T10:20:00Z"),
  });
  const view = buildAutomationRunOutcomeViewModel({
    run,
    now: new Date("2026-05-25T10:20:00Z"),
  });

  assert.equal(stale.stale, true);
  assert.equal(stale.label, "Run still marked in progress");
  assert.equal(view.type, "warning");
  assert.equal(view.headline, "Run still marked in progress");
  assert.match(view.nextAction, /has not recorded a finish time/);
});

test("rerun safety copy covers active assignments baseline waiting and duplicate groups", () => {
  const copy = buildAutomationRerunSafetyCopy({
    includedCount: 2,
    waitingCount: 3,
    skippedCount: 4,
    activeAssignmentCount: 1,
    duplicateCount: 2,
  });

  assert.match(copy, /Already assigned pupils were left untouched/);
  assert.match(copy, /Pupils waiting for baseline can be picked up after baseline completion/);
  assert.match(copy, /Duplicate group memberships were skipped/);
});

test("recent personalised activity rows summarize counts status policy and coverage health", () => {
  const rows = buildRecentPersonalisedRunActivityRows({
    now: new Date("2026-05-25T12:30:00Z"),
    runs: [
      {
        id: "run-old",
        status: "running",
        policy_snapshot: { name: "Older policy", policy_type: "regular_personalised" },
        updated_at: "2026-05-25T11:00:00Z",
        summary: {
          waitingPupilCount: 1,
          classes: [{ waitingCount: 1, waitingReasons: { baseline_incomplete: 1 } }],
        },
        pupilRows: [{ status: "waiting", skip_reason: "baseline_incomplete" }],
      },
      {
        id: "run-new",
        status: "completed",
        included_pupil_count: 4,
        skipped_pupil_count: 2,
        policy_snapshot: { name: "Year 7 weekly", policy_type: "regular_personalised" },
        started_at: "2026-05-25T12:00:00Z",
        finished_at: "2026-05-25T12:05:00Z",
        summary: {
          coverageWarnings: [],
          classes: [{
            includedCount: 4,
            skippedCount: 2,
            skipReasons: {
              active_automated_assignment: 1,
              duplicate_pupil_in_run: 1,
            },
          }],
        },
      },
      {
        id: "bee-run",
        status: "completed",
        policy_snapshot: { name: "Bee", policy_type: "spelling_bee" },
        finished_at: "2026-05-25T12:10:00Z",
      },
    ],
  });

  assert.equal(rows.length, 2);
  assert.equal(rows[0].runId, "run-new");
  assert.equal(rows[0].policyName, "Year 7 weekly");
  assert.equal(rows[0].statusLabel, "Completed");
  assert.equal(rows[0].timestamp, "2026-05-25T12:05:00Z");
  assert.deepEqual(plain(rows[0].counts), {
    generated: 4,
    waiting: 0,
    skipped: 2,
    alreadyAssigned: 1,
  });
  assert.equal(rows[0].coverageHealth.state, "clear");
  assert.equal(rows[1].statusLabel, "Run still marked in progress");
  assert.equal(rows[1].counts.waiting, 1);
});

test("run status and reason labels use teacher-facing copy", () => {
  assert.equal(getAutomationRunStatusLabel("included"), "Generated/provisioned");
  assert.equal(getAutomationRunStatusLabel("waiting"), "Waiting for baseline");
  assert.equal(getAutomationRunStatusLabel("provisioning"), "Provisioning");
  assert.equal(getAutomationRunStatusLabel("completed"), "Completed");
  assert.equal(getAutomationRunStatusLabel("failed"), "Error");
  assert.equal(getAutomationRunReasonLabel("baseline_incomplete"), "Baseline incomplete");
  assert.equal(getAutomationRunReasonLabel("no_baseline_assignment"), "Baseline not created yet");
  assert.equal(getAutomationRunReasonLabel("active_automated_assignment"), "Already assigned");
  assert.equal(getAutomationRunReasonLabel("duplicate_pupil_in_run"), "Duplicate group membership");
});

test("coverage warning display distinguishes missing legacy data from clear new data", () => {
  const missing = buildCoverageWarningDisplay({});
  assert.equal(missing.state, "not_recorded");
  assert.equal(missing.message, "Coverage warnings not recorded for this run.");

  const clear = buildCoverageWarningDisplay({ coverageWarnings: [] });
  assert.equal(clear.state, "clear");
  assert.equal(clear.message, "No coverage warnings recorded for this run.");

  const warning = {
    focusGrapheme: "tion",
    requestedTargetCount: 4,
    selectedTargetCount: 1,
    fallbackCount: 3,
  };
  assert.equal(
    formatCoverageWarningCopy(warning),
    "Only 1 of 4 requested target slots could use approved tion words; 3 slots used safe fallback, review, or consolidation words."
  );
  const display = buildCoverageWarningDisplay({ coverageWarnings: [warning] });
  assert.equal(display.state, "warning");
  assert.equal(display.warnings[0].displayCopy, formatCoverageWarningCopy(warning));
});

test("generated assignment explainability summarizes role mix support mix and focus", () => {
  const summary = buildGeneratedAssignmentExplainabilitySummary({
    sections: [
      {
        key: "review",
        items: [
          { word: "ship", focusGrapheme: "sh", assignmentSupport: "independent", targetReason: "review_retention" },
        ],
      },
      {
        key: "target",
        items: [
          { word: "shop", focusGrapheme: "sh", assignmentSupport: "focus", targetReason: "target_supported" },
          { word: "shed", focusGrapheme: "sh", assignmentSupport: "supported", targetReason: "target_supported" },
        ],
      },
      {
        key: "stretch",
        items: [
          { word: "splash", focusGrapheme: "sh", assignmentSupport: "independent", targetReason: "stretch_probe" },
        ],
      },
    ],
  });

  assert.equal(summary.focusGrapheme, "sh");
  assert.equal(summary.roleMixText, "Review 1, Target 2, Stretch 1");
  assert.equal(summary.supportMixText, "Independent 2, Focus 1, Segmented support 1");
  assert.match(summary.whySentence, /Targets sh with a blend of review, target, and stretch words/);
});

test("generated assignment explainability falls back for missing legacy metadata", () => {
  const summary = buildGeneratedAssignmentExplainabilitySummary({
    words: [{ word: "ship" }, { word: "shop" }],
  });

  assert.equal(summary.focusLabel, "Not recorded");
  assert.equal(summary.roleMixText, "Not recorded");
  assert.equal(summary.supportMixText, "Not recorded");
  assert.equal(summary.whySentence, "Legacy assignment metadata is limited, so only available word details are shown.");
});

for (const { name, fn } of TESTS) {
  await fn();
  console.log(`ok - ${name}`);
}
