alter table if exists public.attempts
  add column if not exists pupil_id uuid,
  add column if not exists test_id uuid,
  add column if not exists test_word_id uuid,
  add column if not exists mode text,
  add column if not exists typed text,
  add column if not exists correct boolean,
  add column if not exists created_at timestamptz not null default timezone('utc', now()),
  add column if not exists assignment_id uuid,
  add column if not exists attempt_number integer,
  add column if not exists attempts_allowed integer,
  add column if not exists word_text text,
  add column if not exists attempt_source text,
  add column if not exists target_graphemes jsonb,
  add column if not exists focus_grapheme text,
  add column if not exists pattern_type text;
